name: "Terraform AWS EC2 Deploy"

on:
  push:
    branches:
      - main
# CRUCIAL: Grants the runner permission to request an OIDC Token from AWS Security Token Service (STS)
permissions:
  id-token: write
  contents: read


jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # ADD THIS STEP HERE (Corrected Directory Path)
      - name: Run Checkov Security Scan
        uses: bridgecrewio/checkov-action@master
        with:
          framework: terraform
          directory: .       # Corrected: Scans the root folder where your main.tf lives
          soft_fail: false   # Blocks the deployment if critical security flaws are found


      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::266408865927:role/github-actions-terraform-executor
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan -out=tfplan.binary

      - name: Convert Plan to JSON
        run: terraform show -json tfplan.binary > tfplan.json

      - name: Setup Conftest
        run: |
          curl -sL https://github.com/open-policy-agent/conftest/releases/download/v0.56.0/conftest_0.56.0_Linux_x86_64.tar.gz | tar xz conftest
          sudo mv conftest /usr/local/bin/

      - name: OPA Policy Gate
        run: conftest test tfplan.json --policy policy/

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan.binary
